config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books
  resources :users, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates :username, presence: true
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_book, only: [:show, :update, :destroy]

  def index
    @books = Book.all
    render json: { status: 'Success', message: 'Books loaded', data: @books }, status: :ok
  end

  def show
    render json: { status: 'Success', message: 'Book found', data: @book }, status: :ok
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      render json: { status: 'Success', message: 'Book created', data: @book }, status: :created
    else
      render json: { status: 'Error', message: 'Book not created', data: @book.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      render json: { status: 'Success', message: 'Book updated', data: @book }, status: :ok
    else
      render json: { status: 'Error', message: 'Book not updated', data: @book.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    render json: { status: 'Success', message: 'Book deleted', data: @book }, status: :ok
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :year )
  end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        user = User.new(user_params)
    
        if user.save
          render json: { message: 'Sign-up successful' }, status: :created
        else
          render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(:username, :email, :password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/form.html.erb
<%= form_with model: @book, url: books_path do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :year %>
      <%= form.number_field :year %>
    </div>
  
    <div class="field">
      <%= form.label :author_id %>
      <%= form.collection_select(:author_id, Author.all, :id, :name) %>
    </div>
  
    <div class="actions">
      <%= form.submit "Tambah Buku" %>
    </div>
  <% end %>
  

app/views/books/index.html.erb
<h1>Daftar Buku</h1>
<table>
  <thead>
    <tr>
      <th>Judul</th>
      <th>Pengarang</th>
      <th>Tahun Terbit</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<%= form_with(model: @book, local: true) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
  
    <%= form.label :year %>
    <%= form.number_field :year %>
  
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, Author.all, :id, :username %>
  
    <%= form.submit 'Create Book' %>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>